name: CICD

on:
  push:
    branches:
      - master

jobs:
  syntax_and_semantic_validation:
    if: ${{ github.event_name == 'push' }}
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Syntax Validation
        run:  echo "Syntax Validation"

      - name: Semantic Validation
        run:  echo "Semantic Validation"

      - name: Run notification.py with parameter A
        run: python notification.py -m syntax_and_semantic_validation
