name: CI/CD

on:
  push:
    branches:
      - neiren
  pull_request:
    branches:
      - 'master'

jobs:
  syntax_and_semantic_validation:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Syntax Validation
        run:  echo "Syntax Validation"

      - name: Semantic Validation
        run:  echo "Semantic Validation"

      - name: Run notification.py with parameter A
        run: python notification.py -m syntax_and_semantic_validation

  pull_request_checks:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Terraform Plan
        run:  echo "terraform plan"

      - name: Run notification.py with parameter B
        run: python notification.py -m pull_request_checks

  merge_to_master:
    if: ${{ github.ref == 'refs/heads/master' && github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    needs: [pull_request_checks]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Terraform Apply
        run:  echo "terraform apply"

      - name: Run notification.py with parameter -m merge_to_master
        run: python notification.py -m merge_to_master
